export const detailData = [
    {
      guid_survey: "SURVEY-001",
      guid_ruas: "RUAS-101",
      ruas: "Jalan A Yani",
      nama_file_video: "GX010380.MP4",
      surveyor: "Budi Santoso",
      tgl_survey: "2024-08-01",
      uploader: "Agus Setiawan",
      tgl_upload: "2024-08-02",
      status: "sudah upload",
    },
    {
      guid_survey: "SURVEY-002",
      guid_ruas: "RUAS-102",
      ruas: "Jalan Sudirman",
      nama_file_video: "GX010381.MP4",
      surveyor: "Andi Wijaya",
      tgl_survey: "2024-08-03",
      uploader: "Rina Apriani",
      tgl_upload: "2024-08-04",
      status: "sudah upload",
    },
    {
      guid_survey: "SURVEY-003",
      guid_ruas: "RUAS-103",
      ruas: "Jalan Diponegoro",
      nama_file_video: "GX010382.MP4",
      surveyor: "Dewi Lestari",
      tgl_survey: "2024-08-05",
      uploader: "",
      tgl_upload: "",
      status: "belum upload",
    },
    {
      guid_survey: "SURVEY-004",
      guid_ruas: "RUAS-104",
      ruas: "Jalan Gatot Subroto",
      nama_file_video: "GX010383.MP4",
      surveyor: "Eka Prasetya",
      tgl_survey: "2024-08-06",
      uploader: "Siti Nurhaliza",
      tgl_upload: "2024-08-07",
      status: "sudah upload",
    },
    {
      guid_survey: "SURVEY-005",
      guid_ruas: "RUAS-105",
      ruas: "Jalan Merdeka",
      nama_file_video: "GX010384.MP4",
      surveyor: "Fajar Ramadhan",
      tgl_survey: "2024-08-08",
      uploader: "",
      tgl_upload: "",
      status: "belum upload",
    },
  ];